feat: Add keybinding for `WindowSwitcherReverse`
pop-os/cosmic-comp pull request #807
Opened 2024-09-03 13:59 UTC by bbb651

See https://github.com/pop-os/cosmic-launcher/pull/183

2024-10-08 02:41 UTC, skylerberg requested changes

2024-10-08 02:41 UTC, skylerberg commented on data/keybindings.ron
>      (modifiers: [Super], key: "Tab"): System(WindowSwitcher),
I believe we should also add Super+Shift+Tab here

2024-10-09 03:10 UTC, skylerberg approved these changes

2025-07-10 12:11 UTC, git-f0x commented
I think this can be closed, since it has been implemented since.

2025-07-10 12:19 UTC, closed without merging